export { http } from './client';
export { auth } from './auth';
export { people } from './people';
export { activities } from './activities';
export { clients } from './clients';
export { regulatory } from './regulatory';
export { stakeholders, institutions, contacts } from './stakeholders';
export { consultations } from './consultations';
export { templates } from './templates';
export { publications } from './publications';
export { membership } from './membership';
export { files } from './files';
export { dashboard } from './dashboard';
export { hr } from './hr';
